window.DinoConfig = {
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 150,
  MAX_DELTA_TIME: 0.1,
  SCORE_DIGITS: 5,
  SCORE_PER_SECOND: 10,
  HIGH_SCORE_STORAGE_KEY: "dino-high-score",

  STATE_IDLE: "idle",
  STATE_RUNNING: "running",
  STATE_GAMEOVER: "gameover",

  PLAYER_IDLE: "idle",
  PLAYER_RUNNING: "running",
  PLAYER_JUMPING: "jumping",
  PLAYER_DUCKING: "ducking",
  PLAYER_GAMEOVER: "gameover",

  DINO_X: 74,
  DINO_WIDTH: 44,
  DINO_HEIGHT: 47,
  DINO_DUCK_HEIGHT: 25,
  DINO_RUN_FRAME_DURATION: 0.1,
  DINO_DUCK_FRAME_DURATION: 0.1,
  GRAVITY: 1700,
  JUMP_VELOCITY: -590,
  FAST_FALL_GRAVITY_MULTIPLIER: 1.6,
  JUMP_RELEASE_GRAVITY_MULTIPLIER: 2.35,
  GROUND_Y: 130,

  WORLD_START_SPEED: 360,
  WORLD_MAX_SPEED: 780,
  WORLD_ACCELERATION_PER_SCORE: 0.48,

  GROUND_LINE_COLOR_DAY: "#8f8f8f",
  GROUND_LINE_COLOR_NIGHT: "#d0d0d0",
  GROUND_PATTERN_COLOR_DAY: "#8a8a8a",
  GROUND_PATTERN_COLOR_NIGHT: "#c8c8c8",
  GROUND_PATTERN_WIDTH: 24,
  GROUND_PATTERN_HEIGHT: 3,
  GROUND_PATTERN_GAP: 18,
  GROUND_PATTERN_OFFSET_Y: 10,

  PLAYER_HITBOX: {
    standing: { insetX: 6, insetTop: 5, insetBottom: 4 },
    ducking: { insetX: 5, insetTop: 3, insetBottom: 3 },
  },

  OBSTACLE_SPAWN_OFFSET_X: 110,
  OBSTACLE_INITIAL_SPAWN_DISTANCE: 420,
  OBSTACLE_MIN_GAP: 235,
  OBSTACLE_MAX_GAP: 410,
  OBSTACLE_GAP_SPEED_REDUCTION: 85,
  OBSTACLE_BIRD_UNLOCK_SCORE: 220,
  OBSTACLE_LOW_BIRD_UNLOCK_SCORE: 360,

  OBSTACLE_DEFINITIONS: [
    {
      id: "cactus-small",
      type: "cactus",
      width: 17,
      height: 35,
      y: 95,
      spriteX: 228,
      spriteY: 2,
      sourceWidth: 17,
      sourceHeight: 35,
      hitbox: { insetX: 1, insetTop: 7, insetBottom: 1 },
      minScore: 0,
    },
    {
      id: "cactus-tall",
      type: "cactus",
      width: 25,
      height: 50,
      y: 80,
      spriteX: 332,
      spriteY: 2,
      sourceWidth: 25,
      sourceHeight: 50,
      hitbox: { insetX: 2, insetTop: 8, insetBottom: 1 },
      minScore: 20,
    },
    {
      id: "cactus-double",
      type: "cactus",
      width: 34,
      height: 35,
      y: 95,
      spriteX: 245,
      spriteY: 2,
      sourceWidth: 34,
      sourceHeight: 35,
      hitbox: { insetX: 1, insetTop: 7, insetBottom: 1 },
      minScore: 70,
    },
    {
      id: "cactus-wide",
      type: "cactus",
      width: 50,
      height: 50,
      y: 80,
      spriteX: 357,
      spriteY: 2,
      sourceWidth: 50,
      sourceHeight: 50,
      hitbox: { insetX: 2, insetTop: 8, insetBottom: 1 },
      minScore: 130,
    },
    {
      id: "bird-mid",
      type: "bird",
      width: 46,
      height: 40,
      y: 56,
      spriteX: 134,
      spriteY: 2,
      sourceWidth: 46,
      sourceHeight: 40,
      frameGap: 46,
      hitbox: { insetX: 4, insetTop: 8, insetBottom: 10 },
      minScore: 220,
    },
    {
      id: "bird-low",
      type: "bird",
      width: 46,
      height: 40,
      y: 81,
      spriteX: 134,
      spriteY: 2,
      sourceWidth: 46,
      sourceHeight: 40,
      frameGap: 46,
      hitbox: { insetX: 4, insetTop: 8, insetBottom: 10 },
      minScore: 360,
    },
  ],

  THEMES: {
    day: {
      skyColor: "#ffffff",
      groundLineColor: "#8f8f8f",
      groundPatternColor: "#8a8a8a",
      textColor: "#535353",
      hintColor: "#757575",
      accentColor: "#535353",
      borderColor: "rgba(83, 83, 83, 0.18)",
      buttonBg: "rgba(255, 255, 255, 0.9)",
      buttonHoverBg: "rgba(245, 245, 245, 0.95)",
      cloudColor: "#d9d9d9",
      cloudShadeColor: "#ededed",
      starColor: "#ffffff",
      moonColor: "#ffffff",
      moonShadeColor: "#ffffff",
      spriteColor: "#535353",
      skylineColor: "#f2f2f2",
    },
    night: {
      skyColor: "#1b1b1b",
      groundLineColor: "#d0d0d0",
      groundPatternColor: "#c8c8c8",
      textColor: "#f0f0f0",
      hintColor: "#d4d4d4",
      accentColor: "#ffffff",
      borderColor: "rgba(255, 255, 255, 0.18)",
      buttonBg: "rgba(24, 24, 24, 0.92)",
      buttonHoverBg: "rgba(40, 40, 40, 0.96)",
      cloudColor: "#4b4b4b",
      cloudShadeColor: "#666666",
      starColor: "#efefef",
      moonColor: "#f7f1c4",
      moonShadeColor: "#c9c29a",
      spriteColor: "#f0f0f0",
      skylineColor: "#242424",
    },
  },

  SCORE_SOUND_MILESTONE: 100,
  STATUS_MESSAGE_DURATION: 1.6,

  SPRITE_CLOUD_X: 86,
  SPRITE_CLOUD_Y: 2,
  SPRITE_CLOUD_WIDTH: 46,
  SPRITE_CLOUD_HEIGHT: 14,
  CLOUD_MIN_Y: 30,
  CLOUD_MAX_Y: 71,
  CLOUD_MIN_GAP: 100,
  CLOUD_MAX_GAP: 400,

  SPRITE_HORIZON_X: 2,
  SPRITE_HORIZON_Y: 54,
  SPRITE_HORIZON_SEGMENT_WIDTH: 600,
  SPRITE_HORIZON_HEIGHT: 12,
  SPRITE_HORIZON_DRAW_Y: 127,

  SPRITE_MOON_X: 484,
  SPRITE_MOON_Y: 2,
  SPRITE_MOON_WIDTH: 20,
  SPRITE_MOON_HEIGHT: 40,
  SPRITE_STAR_X: 645,
  SPRITE_STAR_Y: 2,
  SPRITE_STAR_WIDTH: 9,
  SPRITE_STAR_HEIGHT: 9,
  NIGHT_STAR_COUNT: 4,

  TREX_SPRITE_X: 848,
  TREX_SPRITE_Y: 2,
  TREX_FRAME_WIDTH: 44,
  TREX_FRAME_HEIGHT: 47,
  TREX_RUN_1_X: 88,
  TREX_RUN_2_X: 132,
  TREX_IDLE_X: 44,
  TREX_JUMP_X: 0,
  TREX_DUCK_1_X: 262,
  TREX_DUCK_2_X: 321,
  TREX_DUCK_FRAME_WIDTH: 59,
  TREX_DUCK_FRAME_HEIGHT: 30,

  SPRITE_DIGITS_X: 655,
  SPRITE_DIGITS_Y: 2,
  SPRITE_DIGIT_WIDTH: 10,
  SPRITE_DIGIT_HEIGHT: 11,
  SPRITE_GAME_OVER_X: 655,
  SPRITE_GAME_OVER_Y: 17,
  SPRITE_GAME_OVER_WIDTH: 191,
  SPRITE_GAME_OVER_HEIGHT: 11,
};
