window.DinoConfig = {
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 150,
  MAX_DELTA_TIME: 0.1,
  SCORE_DIGITS: 5,
  HIGH_SCORE_STORAGE_KEY: "dino-high-score",

  STATE_IDLE: "idle",
  STATE_RUNNING: "running",
  STATE_GAMEOVER: "gameover",

  PLAYER_IDLE: "idle",
  PLAYER_RUNNING: "running",
  PLAYER_JUMPING: "jumping",
  PLAYER_DUCKING: "ducking",
  PLAYER_GAMEOVER: "gameover",

  DINO_X: 74,
  DINO_WIDTH: 44,
  DINO_HEIGHT: 47,
  DINO_DUCK_HEIGHT: 25,
  DINO_DUCK_DRAW_OFFSET_X: -7,
  DINO_RUN_FRAME_DURATION: 0.1,
  DINO_DUCK_FRAME_DURATION: 0.125,
  DINO_IDLE_BLINK_DURATION: 0.333,
  DINO_IDLE_BLINK_INTERVAL_MIN: 2.2,
  DINO_IDLE_BLINK_INTERVAL_MAX: 7,
  GRAVITY: 1860,
  JUMP_VELOCITY: -630,
  FAST_FALL_GRAVITY_MULTIPLIER: 1.65,
  JUMP_RELEASE_GRAVITY_MULTIPLIER: 1.85,
  GROUND_Y: 140,
  GAMEOVER_RESTART_DELAY: 1.2,
  INVERT_FADE_DURATION: 12,
  INVERT_DISTANCE: 700,
  INTRO_DURATION: 0.4,
  INTRO_RUNNER_OFFSET: 24,
  COLLISION_BOX_TRIM: 1,

  WORLD_FRAME_RATE: 60,
  WORLD_START_SPEED_FRAMES: 6,
  WORLD_MAX_SPEED_FRAMES: 13,
  WORLD_ACCELERATION_FRAMES: 0.001,
  WORLD_START_SPEED: 360,
  WORLD_MAX_SPEED: 780,
  DISTANCE_SCORE_COEFFICIENT: 0.025,

  GROUND_LINE_COLOR_DAY: "#8f8f8f",
  GROUND_LINE_COLOR_NIGHT: "#d0d0d0",
  GROUND_PATTERN_COLOR_DAY: "#8a8a8a",
  GROUND_PATTERN_COLOR_NIGHT: "#c8c8c8",
  GROUND_PATTERN_WIDTH: 24,
  GROUND_PATTERN_HEIGHT: 3,
  GROUND_PATTERN_GAP: 18,
  GROUND_PATTERN_OFFSET_Y: 10,

  PLAYER_HITBOX: {
    standing: [
      { x: 22, y: 0, width: 17, height: 16 },
      { x: 1, y: 18, width: 30, height: 9 },
      { x: 10, y: 35, width: 14, height: 8 },
      { x: 1, y: 24, width: 29, height: 5 },
      { x: 5, y: 30, width: 21, height: 4 },
      { x: 9, y: 34, width: 15, height: 4 },
    ],
    ducking: [
      { x: 1, y: 18, width: 55, height: 25 },
    ],
  },

  OBSTACLE_SPAWN_OFFSET_X: 0,
  OBSTACLE_CLEAR_TIME: 3,
  OBSTACLE_GAP_COEFFICIENT: 0.6,
  OBSTACLE_MAX_GAP_COEFFICIENT: 1.5,
  OBSTACLE_MAX_DUPLICATION: 2,

  OBSTACLE_DEFINITIONS: [
    {
      id: "cactus-small",
      type: "cactus",
      width: 17,
      height: 35,
      y: 105,
      spriteX: 228,
      spriteY: 2,
      sourceWidth: 17,
      sourceHeight: 35,
      hitboxes: [
        { x: 0, y: 7, width: 5, height: 27 },
        { x: 4, y: 0, width: 6, height: 34 },
        { x: 10, y: 4, width: 7, height: 14 },
      ],
      minSpeed: 0,
      minGap: 120,
    },
    {
      id: "cactus-tall",
      type: "cactus",
      width: 25,
      height: 50,
      y: 90,
      spriteX: 332,
      spriteY: 2,
      sourceWidth: 25,
      sourceHeight: 50,
      hitboxes: [
        { x: 0, y: 12, width: 7, height: 38 },
        { x: 8, y: 0, width: 7, height: 49 },
        { x: 13, y: 10, width: 10, height: 38 },
      ],
      minSpeed: 0,
      minGap: 120,
    },
    {
      id: "cactus-double",
      type: "cactus",
      width: 34,
      height: 35,
      y: 105,
      spriteX: 245,
      spriteY: 2,
      sourceWidth: 34,
      sourceHeight: 35,
      hitboxes: [
        { x: 0, y: 7, width: 5, height: 27 },
        { x: 4, y: 0, width: 6, height: 34 },
        { x: 10, y: 4, width: 7, height: 14 },
        { x: 17, y: 7, width: 5, height: 27 },
        { x: 21, y: 0, width: 6, height: 34 },
        { x: 27, y: 4, width: 7, height: 14 },
      ],
      minSpeed: 4,
      minGap: 120,
    },
    {
      id: "cactus-wide",
      type: "cactus",
      width: 50,
      height: 50,
      y: 90,
      spriteX: 357,
      spriteY: 2,
      sourceWidth: 50,
      sourceHeight: 50,
      hitboxes: [
        { x: 0, y: 12, width: 7, height: 38 },
        { x: 8, y: 0, width: 7, height: 49 },
        { x: 13, y: 10, width: 10, height: 38 },
        { x: 25, y: 12, width: 7, height: 38 },
        { x: 33, y: 0, width: 7, height: 49 },
        { x: 38, y: 10, width: 10, height: 38 },
      ],
      minSpeed: 7,
      minGap: 120,
    },
    {
      id: "bird",
      type: "bird",
      width: 46,
      height: 40,
      y: 100,
      yPositions: [100, 75, 50],
      spriteX: 134,
      spriteY: 2,
      sourceWidth: 46,
      sourceHeight: 40,
      frameGap: 46,
      frameDuration: 1 / 6,
      speedOffset: 48,
      hitboxes: [
        { x: 15, y: 15, width: 16, height: 5 },
        { x: 18, y: 21, width: 24, height: 6 },
        { x: 2, y: 14, width: 4, height: 3 },
        { x: 6, y: 10, width: 4, height: 7 },
        { x: 10, y: 8, width: 6, height: 9 },
      ],
      minSpeed: 8.5,
      minGap: 150,
    },
  ],

  THEMES: {
    day: {
      skyColor: "#ffffff",
      groundLineColor: "#8f8f8f",
      groundPatternColor: "#8a8a8a",
      textColor: "#535353",
      hintColor: "#757575",
      accentColor: "#535353",
      borderColor: "rgba(83, 83, 83, 0.18)",
      buttonBg: "rgba(255, 255, 255, 0.9)",
      buttonHoverBg: "rgba(245, 245, 245, 0.95)",
      cloudColor: "#d9d9d9",
      cloudShadeColor: "#ededed",
      starColor: "#ffffff",
      moonColor: "#ffffff",
      moonShadeColor: "#ffffff",
      spriteColor: "#535353",
      skylineColor: "#f2f2f2",
    },
    night: {
      skyColor: "#1b1b1b",
      groundLineColor: "#d0d0d0",
      groundPatternColor: "#c8c8c8",
      textColor: "#f0f0f0",
      hintColor: "#d4d4d4",
      accentColor: "#ffffff",
      borderColor: "rgba(255, 255, 255, 0.18)",
      buttonBg: "rgba(24, 24, 24, 0.92)",
      buttonHoverBg: "rgba(40, 40, 40, 0.96)",
      cloudColor: "#4b4b4b",
      cloudShadeColor: "#666666",
      starColor: "#efefef",
      moonColor: "#f7f1c4",
      moonShadeColor: "#c9c29a",
      spriteColor: "#f0f0f0",
      skylineColor: "#242424",
    },
  },

  SCORE_SOUND_MILESTONE: 100,
  SCORE_FLASH_DURATION: 0.25,
  SCORE_FLASH_ITERATIONS: 3,
  STATUS_MESSAGE_DURATION: 1.6,

  SPRITE_CLOUD_X: 86,
  SPRITE_CLOUD_Y: 2,
  SPRITE_CLOUD_WIDTH: 46,
  SPRITE_CLOUD_HEIGHT: 14,
  CLOUD_MIN_Y: 30,
  CLOUD_MAX_Y: 71,
  CLOUD_MIN_GAP: 100,
  CLOUD_MAX_GAP: 400,

  SPRITE_HORIZON_X: 2,
  SPRITE_HORIZON_Y: 52,
  SPRITE_HORIZON_SEGMENT_WIDTH: 600,
  SPRITE_HORIZON_HEIGHT: 12,
  SPRITE_HORIZON_DRAW_Y: 127,

  SPRITE_MOON_X: 484,
  SPRITE_MOON_Y: 2,
  SPRITE_MOON_WIDTH: 20,
  SPRITE_MOON_HEIGHT: 40,
  SPRITE_STAR_X: 645,
  SPRITE_STAR_Y: 2,
  SPRITE_STAR_WIDTH: 9,
  SPRITE_STAR_HEIGHT: 9,
  NIGHT_STAR_COUNT: 4,

  TREX_SPRITE_X: 848,
  TREX_SPRITE_Y: 2,
  TREX_FRAME_WIDTH: 44,
  TREX_FRAME_HEIGHT: 47,
  TREX_RUN_1_X: 88,
  TREX_RUN_2_X: 132,
  TREX_IDLE_X: 44,
  TREX_JUMP_X: 0,
  TREX_CRASHED_X: 220,
  TREX_DUCK_1_X: 264,
  TREX_DUCK_2_X: 323,
  TREX_DUCK_FRAME_WIDTH: 59,
  TREX_DUCK_FRAME_HEIGHT: 47,

  SPRITE_DIGITS_X: 655,
  SPRITE_DIGITS_Y: 2,
  SPRITE_DIGIT_WIDTH: 10,
  SPRITE_DIGIT_HEIGHT: 11,
  SPRITE_GAME_OVER_X: 655,
  SPRITE_GAME_OVER_Y: 15,
  SPRITE_GAME_OVER_WIDTH: 191,
  SPRITE_GAME_OVER_HEIGHT: 11,
  SPRITE_GAME_OVER_DRAW_Y: 50,
  SPRITE_RESTART_X: 2,
  SPRITE_RESTART_Y: 68,
  SPRITE_RESTART_WIDTH: 36,
  SPRITE_RESTART_HEIGHT: 32,
  SPRITE_RESTART_DRAW_Y: 82,
};
